export enum ContentType {
  CONCEPT_MAP = "CONCEPT_MAP",
  TIMELINE = "TIMELINE",
  GLOSSARY = "GLOSSARY",
  MATH_PROBLEM = "MATH_PROBLEM",
  SCIENTIFIC_EXPERIMENT = "SCIENTIFIC_EXPERIMENT",
  BOOK_ANALYSIS = "BOOK_ANALYSIS",
  ART_PROJECT = "ART_PROJECT",
  DEBATE = "DEBATE",
  TUTORIAL = "TUTORIAL",
  RESOURCE_COLLECTION = "RESOURCE_COLLECTION",
  OTHER = "OTHER",
}
